---
- name: Simulasi Instalasi via Ansible
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: 1. Update sistem operasi
      apt:
        update_cache: yes

    - name: 2. cek versi docker
      command: docker --version
      register: docker_info

    - name: 3. Tampilkan pesan sukses
      debug:
        msg: "Ansible berhasil menginstal Docker di GitHub Actions!"
